import { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import { Container } from "react-bootstrap";
import { Ubuntu } from "next/font/google";
import "../app/styles/main.scss";
const ubuntu = Ubuntu({
  weight: ["400", "500"], 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={ubuntu.className} >
          <Container className="mx-auto container-max px-0">
            {children}
          </Container>
        </body>
      </html>
    </StoreProvider>
  );
}
